services:
  web:
    restart: always
    image: "ghcr.io/rakbaal/cicd:dev"
    ports:
    - 3001:3000

  db:
    image: mariadb:10.6
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: "yes"
      MARIADB_DATABASE: cube
      MARIADB_USER: cube
      MARIADB_PASSWORD: Noot-Noot
    volumes:
      - ./docker/db/data:/var/lib/mysql

  adminer:
    image: adminer
    ports:
      - 8081:8080