name: build
run-name: ${{ github.actor }} is building and testing
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm install next@latest react@latest react-dom@latest
      - run: npm i
      - run: npm run build
      - run: npm run e2e:headless