name: build
run-name: ${{ github.actor }} is building and testing
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout 
        uses: actions/checkout@v3
      - name: setup
        run: |
          npm install next@latest react@latest react-dom@latest 
          npm i
      - name: building
        run: npm run build
      - name: running cypress tests
        run: npm run e2e:headless
      - name: saving video as artifact
        uses: actions/upload-artifact@v3
        with:
          name: video
          path: cypress/videos/app.cy.ts.mp4