name: dockerize
run-name: ${{github.actor}} is building the container
on: [push]

jobs:
    # build-push:
    #     runs-on: ubuntu-latest
    #     permissions:
    #         contents: read
    #         packages: write
    #     steps:
    #         - name: login to docker registry
    #           uses: docker/login-action@v2
    #           with:
    #             registry: ghcr.io
    #             username: ${{github.actor}}
    #             password: ${{secrets.GITHUB_TOKEN}}
    #             logout: false
    #         - name: Build and push
    #           uses: docker/build-push-action@v4
    #           with:
    #             push: true
    #             tags: ghcr.io/rakbaal/cicd:latest 
    deploy-image:
        runs-on: ubuntu-latest
        needs: build-push
        steps:
            - name: save private key
              uses: webfactory/ssh-agent@v0.8.0
              with:
                ssh-private-key: ${{secrets.SSH_KEY}}
            - name: ssh connection
              run: ssh -o StrictHostKeyChecking=no ${{secrets.SSH_USER}}@${{secrets.DNS_ADDRESS}} "sudo docker system prune -f && docker pull ghcr.io/rakbaal/cicd && sudo docker run -d -p 3000:3000 --name next ghcr.io/rakbaal/cicd" 

            